services:
  crater-detection-app:
    build: .
    container_name: crater_detection_app
    ports:
      - "${CRATER_DETECTION_PORT:-8000}:8000"  # Map the container port 8000 to the host port specified in the env variable or default to 8000
    volumes:
      - "${CRATER_DETECTION_DATA_VOLUME:-./data}:/app/data"  # Volume for sharing the `data` folder
    command: >
      uvicorn src.presentation.api.main:app --host 0.0.0.0 --port 8000
